version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
    environment:
      cluster.name: elastic-pro
      node.name: node_master
      node.master: "true" 
      node.data: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk

  elasticsearch2:
    build:
      context: elasticsearch2/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch2/config/elasticsearch.yml:/usr/share/elasticsearch2/config/elasticsearch.yml:ro  
    ports:
      - "9202:9200"
      - "9302:9300"
    container_name: elasticsearch2
    environment:
      cluster.name: elastic-pro
      node.name: node2
      node.master: "false"
      node.data: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk 

  elasticsearch3:
    build:
      context: elasticsearch3/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch3/config/elasticsearch.yml:/usr/share/elasticsearch3/config/elasticsearch.yml:ro
    ports:
      - "9203:9200"
      - "9303:9300"
    container_name: elasticsearch3
    environment:
      cluster.name: elastic-pro
      node.name: node3
      node.master: "false"
      node.data: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
